logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/lingxi
  jpa:
    generate-ddl: true
    show-sql: true

custom:
  jwt-secret: ${JWT_SECRET:lingxi_jwt}
springdoc:
  api-docs:
    version: openapi_3_0
    path: /v3/api-docs
  swagger-ui:
#    config-url: /v3/api-docs/swagger-config
    disable-swagger-default-url: false
    url: /v3/api-docs
    doc-expansion: none
    query-config-enabled: true